export enum PokemonTypeEnum {
  NORMAL = 'Normal',
  FIGHTING = 'Lutador',
  FLYING = 'Voador',
  POISON = 'Venenoso',
  GROUND = 'Lutador',
  ROCK = 'Rocha',
  BUG = 'Inseto',
  GHOST = 'Fastasma',
  STEEL = 'Aço',
  FIRE = 'Fogo',
  WATER = 'Água',
  GRASS = 'Relva',
  ELECTRIC = 'Elétrico',
  PSYCHIC = 'Psíquico',
  ICE = 'Gelo',
  DRAGON = 'Dragão',
  DARK = 'Sombrio',
  FAIRY = 'Fada',
  UNKNOWN = 'Desconhecido',
  SHADOW = 'Sombra'
}
