export enum PokemonColorEnum {
  GRASS = '#d2f2c2',
  POISON = '#f7cdf7',
  FIRE = '#ffd1b5',
  FLYING = '#eae3ff',
  WATER = '#c2f3ff',
  BUG = '#e0e8a2',
  NORMAL = '#e6e6c3',
  ELETRIC = '#fff1ba',
  GROUND = '#e0ccb1',
  FIGHTING = '#fcada9',
  PSYCHIC = '#ffc9da',
  ROCK = '#f0e09c',
  FAIRY = '#ffdee5',
  STEEL = '#e6eaf0',
  ICE = '#e8feff',
  GHOST = '#dbbaff',
  DRAGON = '#c4bdff',
  DARK = '#a9abb0'
}
